package com.github.supavitax.itemlorestats.Util;

import org.bukkit.Material;

public class Util_Material {
    public double materialToDamage(Material mat) {
        return mat != Material.WOOD_SPADE && mat != Material.GOLD_SPADE ? (mat != Material.WOOD_PICKAXE && mat != Material.GOLD_PICKAXE && mat != Material.STONE_SPADE ? (mat != Material.WOOD_AXE && mat != Material.GOLD_AXE && mat != Material.STONE_PICKAXE && mat != Material.IRON_SPADE ? (mat != Material.WOOD_SWORD && mat != Material.GOLD_SWORD && mat != Material.STONE_AXE && mat != Material.IRON_PICKAXE && mat != Material.DIAMOND_SPADE ? (mat != Material.STONE_SWORD && mat != Material.IRON_AXE && mat != Material.DIAMOND_PICKAXE ? (mat != Material.IRON_SWORD && mat != Material.DIAMOND_AXE ? (mat == Material.DIAMOND_SWORD ? 8.0D : 1.0D) : 7.0D) : 6.0D) : 5.0D) : 4.0D) : 3.0D) : 2.0D;
    }

    public String materialToId(Material mat) {
        String customMaterial = mat.toString().split(":")[0];
        return mat != null ? (mat == Material.IRON_SPADE ? "256" : (mat == Material.IRON_PICKAXE ? "257" : (mat == Material.IRON_AXE ? "258" : (mat == Material.FLINT_AND_STEEL ? "259" : (mat == Material.BOW ? "261" : (mat == Material.IRON_SWORD ? "267" : (mat == Material.WOOD_SWORD ? "268" : (mat == Material.WOOD_SPADE ? "269" : (mat == Material.WOOD_PICKAXE ? "270" : (mat == Material.WOOD_AXE ? "271" : (mat == Material.STONE_SWORD ? "272" : (mat == Material.STONE_SPADE ? "273" : (mat == Material.STONE_PICKAXE ? "274" : (mat == Material.STONE_AXE ? "275" : (mat == Material.DIAMOND_SWORD ? "276" : (mat == Material.DIAMOND_SPADE ? "277" : (mat == Material.DIAMOND_PICKAXE ? "278" : (mat == Material.DIAMOND_AXE ? "279" : (mat == Material.STICK ? "280" : (mat == Material.GOLD_SWORD ? "283" : (mat == Material.GOLD_SPADE ? "284" : (mat == Material.GOLD_PICKAXE ? "285" : (mat == Material.GOLD_AXE ? "286" : (mat == Material.STRING ? "287" : (mat == Material.WOOD_HOE ? "290" : (mat == Material.STONE_HOE ? "291" : (mat == Material.IRON_HOE ? "292" : (mat == Material.DIAMOND_HOE ? "293" : (mat == Material.GOLD_HOE ? "294" : (mat == Material.LEATHER_HELMET ? "298" : (mat == Material.LEATHER_CHESTPLATE ? "299" : (mat == Material.LEATHER_LEGGINGS ? "300" : (mat == Material.LEATHER_BOOTS ? "301" : (mat == Material.CHAINMAIL_HELMET ? "302" : (mat == Material.CHAINMAIL_CHESTPLATE ? "303" : (mat == Material.CHAINMAIL_LEGGINGS ? "304" : (mat == Material.CHAINMAIL_BOOTS ? "305" : (mat == Material.IRON_HELMET ? "306" : (mat == Material.IRON_CHESTPLATE ? "307" : (mat == Material.IRON_LEGGINGS ? "308" : (mat == Material.IRON_BOOTS ? "309" : (mat == Material.DIAMOND_HELMET ? "310" : (mat == Material.DIAMOND_CHESTPLATE ? "311" : (mat == Material.DIAMOND_LEGGINGS ? "312" : (mat == Material.DIAMOND_BOOTS ? "313" : (mat == Material.GOLD_HELMET ? "314" : (mat == Material.GOLD_CHESTPLATE ? "315" : (mat == Material.GOLD_LEGGINGS ? "316" : (mat == Material.GOLD_BOOTS ? "317" : (mat == Material.SHEARS ? "359" : (mat == Material.BLAZE_ROD ? "369" : customMaterial))))))))))))))))))))))))))))))))))))))))))))))))))) : "ERROR";
    }

    public Material idToMaterial(String id) {
        String customMaterial = id.split(":")[0];
        return id != null ? ("256".equals(id) ? Material.IRON_HOE : ("257".equals(id) ? Material.IRON_PICKAXE : ("258".equals(id) ? Material.IRON_AXE : ("261".equals(id) ? Material.BOW : ("267".equals(id) ? Material.IRON_SWORD : ("268".equals(id) ? Material.WOOD_SWORD : ("269".equals(id) ? Material.WOOD_SPADE : ("270".equals(id) ? Material.WOOD_PICKAXE : ("271".equals(id) ? Material.WOOD_AXE : ("272".equals(id) ? Material.STONE_SWORD : ("273".equals(id) ? Material.STONE_SPADE : ("274".equals(id) ? Material.STONE_PICKAXE : ("275".equals(id) ? Material.STONE_AXE : ("276".equals(id) ? Material.DIAMOND_SWORD : ("277".equals(id) ? Material.DIAMOND_SPADE : ("278".equals(id) ? Material.DIAMOND_PICKAXE : ("279".equals(id) ? Material.DIAMOND_AXE : ("280".equals(id) ? Material.STICK : ("283".equals(id) ? Material.GOLD_SWORD : ("284".equals(id) ? Material.GOLD_SPADE : ("285".equals(id) ? Material.GOLD_PICKAXE : ("286".equals(id) ? Material.GOLD_AXE : ("287".equals(id) ? Material.STRING : ("290".equals(id) ? Material.WOOD_HOE : ("291".equals(id) ? Material.STONE_HOE : ("292".equals(id) ? Material.IRON_HOE : ("293".equals(id) ? Material.DIAMOND_HOE : ("294".equals(id) ? Material.GOLD_HOE : ("298".equals(id) ? Material.LEATHER_HELMET : ("299".equals(id) ? Material.LEATHER_CHESTPLATE : ("300".equals(id) ? Material.LEATHER_LEGGINGS : ("301".equals(id) ? Material.LEATHER_BOOTS : ("302".equals(id) ? Material.CHAINMAIL_HELMET : ("303".equals(id) ? Material.CHAINMAIL_CHESTPLATE : ("304".equals(id) ? Material.CHAINMAIL_LEGGINGS : ("305".equals(id) ? Material.CHAINMAIL_BOOTS : ("306".equals(id) ? Material.IRON_HELMET : ("307".equals(id) ? Material.IRON_CHESTPLATE : ("308".equals(id) ? Material.IRON_LEGGINGS : ("309".equals(id) ? Material.IRON_BOOTS : ("310".equals(id) ? Material.DIAMOND_HELMET : ("311".equals(id) ? Material.DIAMOND_CHESTPLATE : ("312".equals(id) ? Material.DIAMOND_LEGGINGS : ("313".equals(id) ? Material.DIAMOND_BOOTS : ("314".equals(id) ? Material.GOLD_HELMET : ("315".equals(id) ? Material.GOLD_CHESTPLATE : ("316".equals(id) ? Material.GOLD_LEGGINGS : ("317".equals(id) ? Material.GOLD_BOOTS : ("359".equals(id) ? Material.SHEARS : ("369".equals(id) ? Material.BLAZE_ROD : ("397".equals(id) ? Material.SKULL_ITEM : Material.getMaterial(customMaterial)))))))))))))))))))))))))))))))))))))))))))))))))))) : Material.POTATO;
    }
}
