package com.github.supavitax.itemlorestats.Util;

import org.bukkit.Material;

public class Util_Material {

    public double materialToDamage(Material mat) {
        return mat != Material.WOOD_SPADE && mat != Material.GOLD_SPADE ? (mat != Material.WOOD_PICKAXE && mat != Material.GOLD_PICKAXE && mat != Material.STONE_SPADE ? (mat != Material.WOOD_AXE && mat != Material.GOLD_AXE && mat != Material.STONE_PICKAXE && mat != Material.IRON_SPADE ? (mat != Material.WOOD_SWORD && mat != Material.GOLD_SWORD && mat != Material.STONE_AXE && mat != Material.IRON_PICKAXE && mat != Material.DIAMOND_SPADE ? (mat != Material.STONE_SWORD && mat != Material.IRON_AXE && mat != Material.DIAMOND_PICKAXE ? (mat != Material.IRON_SWORD && mat != Material.DIAMOND_AXE ? (mat == Material.DIAMOND_SWORD ? 8.0D : 1.0D) : 7.0D) : 6.0D) : 5.0D) : 4.0D) : 3.0D) : 2.0D;
    }

    public String materialToId(Material mat) {
        String customMaterial = mat.toString().split(":")[0];
        return mat != null ? (mat == Material.IRON_SPADE ? "256" : (mat == Material.IRON_PICKAXE ? "257" : (mat == Material.IRON_AXE ? "258" : (mat == Material.FLINT_AND_STEEL ? "259" : (mat == Material.BOW ? "261" : (mat == Material.IRON_SWORD ? "267" : (mat == Material.WOOD_SWORD ? "268" : (mat == Material.WOOD_SPADE ? "269" : (mat == Material.WOOD_PICKAXE ? "270" : (mat == Material.WOOD_AXE ? "271" : (mat == Material.STONE_SWORD ? "272" : (mat == Material.STONE_SPADE ? "273" : (mat == Material.STONE_PICKAXE ? "274" : (mat == Material.STONE_AXE ? "275" : (mat == Material.DIAMOND_SWORD ? "276" : (mat == Material.DIAMOND_SPADE ? "277" : (mat == Material.DIAMOND_PICKAXE ? "278" : (mat == Material.DIAMOND_AXE ? "279" : (mat == Material.STICK ? "280" : (mat == Material.GOLD_SWORD ? "283" : (mat == Material.GOLD_SPADE ? "284" : (mat == Material.GOLD_PICKAXE ? "285" : (mat == Material.GOLD_AXE ? "286" : (mat == Material.STRING ? "287" : (mat == Material.WOOD_HOE ? "290" : (mat == Material.STONE_HOE ? "291" : (mat == Material.IRON_HOE ? "292" : (mat == Material.DIAMOND_HOE ? "293" : (mat == Material.GOLD_HOE ? "294" : (mat == Material.LEATHER_HELMET ? "298" : (mat == Material.LEATHER_CHESTPLATE ? "299" : (mat == Material.LEATHER_LEGGINGS ? "300" : (mat == Material.LEATHER_BOOTS ? "301" : (mat == Material.CHAINMAIL_HELMET ? "302" : (mat == Material.CHAINMAIL_CHESTPLATE ? "303" : (mat == Material.CHAINMAIL_LEGGINGS ? "304" : (mat == Material.CHAINMAIL_BOOTS ? "305" : (mat == Material.IRON_HELMET ? "306" : (mat == Material.IRON_CHESTPLATE ? "307" : (mat == Material.IRON_LEGGINGS ? "308" : (mat == Material.IRON_BOOTS ? "309" : (mat == Material.DIAMOND_HELMET ? "310" : (mat == Material.DIAMOND_CHESTPLATE ? "311" : (mat == Material.DIAMOND_LEGGINGS ? "312" : (mat == Material.DIAMOND_BOOTS ? "313" : (mat == Material.GOLD_HELMET ? "314" : (mat == Material.GOLD_CHESTPLATE ? "315" : (mat == Material.GOLD_LEGGINGS ? "316" : (mat == Material.GOLD_BOOTS ? "317" : (mat == Material.SHEARS ? "359" : (mat == Material.BLAZE_ROD ? "369" : customMaterial))))))))))))))))))))))))))))))))))))))))))))))))))) : "ERROR";
    }

    public Material idToMaterial(String id) {
        String customMaterial = id.toString().split(":")[0];
        return id != null ? (id.equals("256") ? Material.IRON_HOE : (id.equals("257") ? Material.IRON_PICKAXE : (id.equals("258") ? Material.IRON_AXE : (id.equals("261") ? Material.BOW : (id.equals("267") ? Material.IRON_SWORD : (id.equals("268") ? Material.WOOD_SWORD : (id.equals("269") ? Material.WOOD_SPADE : (id.equals("270") ? Material.WOOD_PICKAXE : (id.equals("271") ? Material.WOOD_AXE : (id.equals("272") ? Material.STONE_SWORD : (id.equals("273") ? Material.STONE_SPADE : (id.equals("274") ? Material.STONE_PICKAXE : (id.equals("275") ? Material.STONE_AXE : (id.equals("276") ? Material.DIAMOND_SWORD : (id.equals("277") ? Material.DIAMOND_SPADE : (id.equals("278") ? Material.DIAMOND_PICKAXE : (id.equals("279") ? Material.DIAMOND_AXE : (id.equals("280") ? Material.STICK : (id.equals("283") ? Material.GOLD_SWORD : (id.equals("284") ? Material.GOLD_SPADE : (id.equals("285") ? Material.GOLD_PICKAXE : (id.equals("286") ? Material.GOLD_AXE : (id.equals("287") ? Material.STRING : (id.equals("290") ? Material.WOOD_HOE : (id.equals("291") ? Material.STONE_HOE : (id.equals("292") ? Material.IRON_HOE : (id.equals("293") ? Material.DIAMOND_HOE : (id.equals("294") ? Material.GOLD_HOE : (id.equals("298") ? Material.LEATHER_HELMET : (id.equals("299") ? Material.LEATHER_CHESTPLATE : (id.equals("300") ? Material.LEATHER_LEGGINGS : (id.equals("301") ? Material.LEATHER_BOOTS : (id.equals("302") ? Material.CHAINMAIL_HELMET : (id.equals("303") ? Material.CHAINMAIL_CHESTPLATE : (id.equals("304") ? Material.CHAINMAIL_LEGGINGS : (id.equals("305") ? Material.CHAINMAIL_BOOTS : (id.equals("306") ? Material.IRON_HELMET : (id.equals("307") ? Material.IRON_CHESTPLATE : (id.equals("308") ? Material.IRON_LEGGINGS : (id.equals("309") ? Material.IRON_BOOTS : (id.equals("310") ? Material.DIAMOND_HELMET : (id.equals("311") ? Material.DIAMOND_CHESTPLATE : (id.equals("312") ? Material.DIAMOND_LEGGINGS : (id.equals("313") ? Material.DIAMOND_BOOTS : (id.equals("314") ? Material.GOLD_HELMET : (id.equals("315") ? Material.GOLD_CHESTPLATE : (id.equals("316") ? Material.GOLD_LEGGINGS : (id.equals("317") ? Material.GOLD_BOOTS : (id.equals("359") ? Material.SHEARS : (id.equals("369") ? Material.BLAZE_ROD : (id.equals("397") ? Material.SKULL_ITEM : Material.getMaterial(customMaterial)))))))))))))))))))))))))))))))))))))))))))))))))))) : Material.POTATO;
    }
}
