main: com.github.supavitax.itemlorestats.ItemLoreStats
name: ItemLoreStats
version: 6.2.2
author: Supavitax
website: http://dev.bukkit.org/profiles/Supavitax/
description: Increase attributes with Item Lore Stats.
softdepend: [WorldGuard, Vault, Heroes, BarAPI, BossBarAPI, SkillAPI, Citizens]

commands:
  ils:
    description: The core ILS command.

permissions:
  ils.admin: 
    description: Player/group is granted admin privilege.
    default: op
  ils.repair:
    description: Allows players to use the /ils repair command.
    default: op